# Generated by Django 5.1 on 2024-08-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('main_question', models.TextField()),
                ('additional_questions', models.ManyToManyField(blank=True, to='accounts.additionalquestion')),
            ],
        ),
    ]
