# Generated by Django 5.1 on 2024-08-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='success_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
