# Generated by Django 5.1 on 2024-08-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_question_success_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='success_image',
            field=models.ImageField(blank=True, null=True, upload_to='success_images/'),
        ),
    ]
