# Generated by Django 5.1 on 2024-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_additionalquestion_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quests',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.quest'),
        ),
    ]
