# Generated by Django 5.1 on 2024-08-14 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalquestion',
            name='correct_answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quest',
            name='main_question_answer',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='QuestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_question_answer', models.TextField()),
                ('additional_question_answers', models.JSONField(default=dict)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
