# Generated by Django 5.1 on 2024-08-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_additionalquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='description',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='additional_questions',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='main_question',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='main_question_answer',
        ),
        migrations.AddField(
            model_name='quest',
            name='correct_answer',
            field=models.CharField(default='default_answer', max_length=200),
        ),
        migrations.AlterField(
            model_name='quest',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='QuestAnswer',
        ),
    ]
